spring:
  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
        namespace: b9cf435e-d360-4047-8f85-b43ccadfb2e0
  config:
    import:
      - optional:nacos:dev.yml