server:
  port: 8081
spring:
  redis:
    host: 192.168.11.228
    port: 6379
    database: 5
    lettuce:
      pool:
        max-active: 8  #最大连接数
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
        max-idle: 8 #最大空闲