spring:
  rabbitmq:
    host: txynode01
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual #开启手动ack
        prefetch: 10 #每次消费10条
    publisher-confirm-type: correlated  #开启confirm机制,保证数据到达交换机
    publisher-returns: true #开启return机制,保证数据到达队列